POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Ruchitha",
  "email": "ruchitha@test.com",
  "password": "123456"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ruchitha@test.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTljNjY0OTQ2NmM0NzA0NTZmNGJiM2YiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzE4NTc5NzksImV4cCI6MTc3MjQ2Mjc3OX0.KqzaM3LwNKsvjubmY-qqusxFkxvx5WUYG-NoJbGNwgM


file=C:\Users\RUCHITHA\Desktop\sample.pdf